### ISSUE TITLE
Update frequency from Petfinder

### ISSUE THREAD

**Issue by kfajans** [cferdinandi/fetch#10]
My client noticed a difference between her Petfinder listings and the ones on her website. It looks like they were the two newest listings. Can you tell me how often the feed from Petfinder gets updated?

**Comment by cferdinandi** [comment]
Fetch requests new data in real time when you first visit your listings from a specific device, and saves that data for an hour. So for example, if you visited your listings a 2:30pm, Fetch would ask for new data from Petfinder on that computer from that browser after 3:30pm. However, if you visited the site again on your smartphone at 2:45pm, it would get fresh data and then request again on that device after 3:45pm.

If your client is noticing longer delays, it's likely due to the data from the API itself. I believe they update their data feed less frequently than their website. You would need to contact them to find out.
