### ISSUE TITLE
No images

### ISSUE THREAD

**Issue by dstrussell** [cferdinandi/fetch#20]
Using as a plugin. No placeholders, nothing to indicate an image is there. Attached is Fetch page and also PetFinder page. Same results with and without VPN enabled. Host is DreamHost. Version of WordPress is the latest. Any insight?

![fetchplugin](https://user-images.githubusercontent.com/14256012/49329492-0164e600-f53d-11e8-95c8-b6fa5517197a.jpg)
![pets](https://user-images.githubusercontent.com/14256012/49329493-0a55b780-f53d-11e8-9aec-fb020be1ed03.jpg)

**Comment by cferdinandi** [comment]
Do you have a link to your site so I can take a look? This should not be happening.

**Comment by dstrussell** [comment]
[https://whiskersutah.org/pets/](url)

**Comment by cferdinandi** [comment]
Looks like your WordPress theme stylesheet has a style setting the `font-size` property for `img` elements to `0`.

Because of how Fetch sizes images, this results in images that have a height/width of 0px. They're actually being loaded on the page, but they're not being shown.

You can comment out line 241 of `style.css` (not recommended, since any theme updates will wipe it back out), or add this to your site instead:

```css
.fetch-container img {
    font-size: 1em;
}
```

The Jetpack plugin from Automattic has a feature you can use to add CSS to your site. After activating it, you can go to `Appearance > Customize` to find it.

Hope that helps!

**Comment by cferdinandi** [comment]
Oh sure, that works, too!

Glad this was an easy fix. Have a great week!
