### ISSUE TITLE
Not displaying All Pets

### ISSUE THREAD

**Issue by spisbell** [cferdinandi/fetch#5]
Hello Support!

I'm currently working on a WordPress site and it seems that not every pet is being pulled in. I noticed it when I wasn't seeing any animals without a photo being pulled in. I looked on Petfinder and I noticed a lot more pets are listed there than whats being pulled into our site. 

For example here's our cat page: http://dev.warmhearts.org/adoptable-cats/
The shortcode to display cats: [fetch key="8d722cd3f54805c0772e32a620688d44" shelter="AR51" allpetstitle="Adoptable Cats" filteranimals="false"]
Cats on Petfinder: https://www.petfinder.com/search/cats-for-adoption/?shelter_id%5B0%5D=AR51

Maybe I'm something is being filtered and I don't know about it?
P.S. I am displaying only cats using your suggestion here: https://github.com/cferdinandi/fetch/issues/3
Thanks In Advance for your help.
Scarlett

**Comment by cferdinandi** [comment]
This one is probably less obvious because you're also pulling in dogs but hiding them visually: you're not pulling enough entries from the Petfinder API. If you bump up the default `count` to `50` or `100`, all of your cats show up.

```
 [fetch key="ABC1234" shelter="AR51" allpetstitle="Adoptable Cats" filteranimals="false" count="75"]
```

The one problem you'll face: there's currently no replacement of broken or missing images in Fetch. Definitely a feature I can/should add.

*__PS:__ I scrubbed your key from your original message. You should keep those private, as they're unique to you and your account.*

**Comment by spisbell** [comment]
That did the trick! 
I will be looking forward to the image fix as well. 

Thanks so much!
